// Cloudflare Pages Functions' built-in bundler has no loader for `.md`
// imports, so this generates a .ts module re-exporting each prompts/*.md
// file's raw content as a string constant. prompts/*.md remains the
// single source of truth for humans editing prompt text (SPEC.md 5節);
// this generated file is a build artifact (gitignored), regenerated by
// `npm run build` / `npm run pages:dev` before every run.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));
const promptsDir = join(rootDir, "prompts");
const outFile = join(rootDir, "functions/api/_lib/prompts.generated.ts");

function toConstName(filename) {
  return (
    filename
      .replace(/\.md$/, "")
      .replace(/-([a-z])/g, (_, c) => c.toUpperCase())
      .replace(/^([a-z])/, (_, c) => c.toUpperCase())
      .replace(/Agent$/, "_AGENT")
      .replace(/Writer$/, "_WRITER")
      .toUpperCase() + "_PROMPT"
  );
}

const files = readdirSync(promptsDir).filter((f) => f.endsWith(".md"));
const lines = [
  "// Generated by scripts/generate-prompts.mjs — do not edit by hand.",
  "// Edit the source files in prompts/*.md instead.",
  "",
];
for (const file of files) {
  const content = readFileSync(join(promptsDir, file), "utf-8");
  lines.push(`export const ${toConstName(file)} = ${JSON.stringify(content)};`);
}
writeFileSync(outFile, lines.join("\n") + "\n");
console.log(`Generated ${outFile} from ${files.length} prompt file(s).`);
